- agent/agent/alert/alert.go
- agent/cli/export.go
- agent/cli/import.go
- agent/cli/promote.go
- agent/cli/proxy.go
- agent/cli/quota.go
- agent/cli/rename.go
- agent/cli/stats.go
- agent/lib/container/lxc.go
- agent/lib/fs/btrfs.go
- agent/lib/template/management.go
- agent/lib/template/template.go
> Revert "Support of setting single disk quota for whole container"

- agent/agent/alert/alert.go
- agent/cli/export.go
- agent/cli/import.go
- agent/cli/promote.go
- agent/cli/proxy.go
- agent/cli/quota.go
- agent/cli/rename.go
- agent/cli/stats.go
- agent/lib/container/lxc.go
- agent/lib/fs/btrfs.go
- agent/lib/template/management.go
- agent/lib/template/template.go
> Revert "Revert "Support of setting single disk quota for whole container""

- management/server/core/peer-manager/peer-manager-api/src/main/java/io/subutai/core/peer/api/PeerManager.java
- management/server/core/peer-manager/peer-manager-cli/src/main/java/io/subutai/core/peer/cli/SetPublicUrlCommand.java
- management/server/core/peer-manager/peer-manager-cli/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
* added setPublicUrl API
* implemented setPublicUrl
* implemented setPublicUrl CLI
> Added set public url API to peer manager module

- management/server/webui-impl/src/main/resources/subutai-app.js
fixed rest for registration to hub
> fixed rest for registration to HUB

- management/server/webui/src/main/webapp/subutai-app/bazaar/controller.js
- management/server/webui/src/main/webapp/subutai-app/bazaar/partials/hub.html
- management/server/webui/src/main/webapp/subutai-app/bazaar/partials/view.html
Added Refresh routine for Bazaar
> Bazaar refresh bug

- management/server/server-karaf/pom.xml
now you need to add -P deb to mvn clean install cmd to have it
> made building debian file optional

- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/AdvancedSettings.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/pojo/AdvancedSettingsPojo.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/subutai-app/common/partials/nav-menu.html
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/service.js
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/settingsAdvanced.js
added advanced settings with karaf logs
> System manager

- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/NetworkSettings.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/pojo/NetworkSettingsPojo.java
- management/server/core/system-manager/system-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/server-karaf/src/main/assembly/etc/subutaisystem.cfg
- management/server/subutai-common/src/main/java/io/subutai/common/settings/SystemSettings.java
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/partials/quotas.html
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/partials/urls.html
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/service.js
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/service.js
added publicUrl to System Settings
> added publicUrl to System Settings

- management/server/webui/src/main/webapp/subutai-app/environment/controller.js
environment creation null pointer exception fix
> Front end devel

- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> Environment creation trigger added

- management/server/core/channel-manager/channel-manager-api/src/main/java/io/subutai/core/channel/api/ChannelManager.java
- management/server/core/channel-manager/channel-manager-impl/src/main/java/io/subutai/core/channel/impl/ChannelManagerImpl.java
- management/server/core/channel-manager/channel-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/ConfigManager.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/IntegrationImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/identity-manager/identity-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/kurjun/kurjun-impl/src/main/java/io/subutai/core/kurjun/impl/TemplateManagerImpl.java
- management/server/core/kurjun/kurjun-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/object-relation-manager/object-relation-manager-impl/src/main/java/io/subutai/core/object/relation/impl/RelationInfoManagerImpl.java
- management/server/core/object-relation-manager/object-relation-manager-impl/src/main/java/io/subutai/core/object/relation/impl/RelationManagerImpl.java
- management/server/core/object-relation-manager/object-relation-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/security-manager/security-manager-impl/src/main/java/io/subutai/core/security/impl/SecurityManagerImpl.java
- management/server/core/security-manager/security-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/subutai-common/src/main/java/io/subutai/common/settings/SystemSettings.java
Clean up modules from fetching configurations  peer.cfg properties file.
> Clean up modules from fetching configurations  peer.cfg properties file.

- agent/agent/agent.go
> Updated registration mechanism

- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/css/style.css
- management/server/webui/src/main/webapp/subutai-app/common/partials/hubSuccessMessage.html
- management/server/webui/src/main/webapp/subutai-app/identityRole/controller.js
- management/server/webui/src/main/webapp/subutai-app/identityUser/controller.js
- management/server/webui/src/main/webapp/subutai-app/peerRegistration/controller.js
> User page fixes

- management/server/core/hub-manager/hub-manager-impl/pom.xml
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/IntegrationImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/proccessors/HubLoggerProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
Sending System logs to Hub finished
> Configuration sender

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/ProxyContainerHelper.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/ProxyEnvironmentContainer.java
Tested on single peer with two containers
> Hub env post build

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/dao/EnvironmentDataService.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/creation/EnvironmentCreationWorkflow.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/creation/steps/ContainerCloneStep.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/AbstractResponseCollector.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/CreateEnvironmentContainerResponseCollector.java
- management/server/subutai-common/src/main/java/io/subutai/common/task/ResponseCollector.java
…fixes
#	management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
> store cloned containers

- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/security/crypto/pgp/PGPEncryptionUtil.java
- management/server/webui/src/main/webapp/subutai-app/accountSettings/controller.js
- management/server/webui/src/main/webapp/subutai-app/accountSettings/partials/view.html
Permissions delegate process moved to plugin, now full delegation process is handled by e2e-plugin
> User permissions delegate

- management/server/webui/src/main/webapp/subutai-app/peerRegistration/controller.js
#380 fixed, old code conflicts removed
> #380 fixed, old code conflicts removed

- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/index.html
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
- management/server/webui/src/main/webapp/subutai-app/kurjun/service.js
> kurjun ui hotfix

- 1
- management/server/webui/src/main/webapp/subutai-app/kurjun/service.js
> angularjs KURJUN_URL fix

- management/server/webui/src/main/webapp/css/style.css
- management/server/webui/src/main/webapp/subutai-app/containers/partials/view.html
added custom classes for e2e
TODO will fix later
made ez-ssh btn visible for all cases
> corrected style

- management/server/core/kurjun-manager/kurjun-manager-api/src/main/java/io/subutai/core/kurjun/manager/api/KurjunManager.java
- management/server/core/kurjun-manager/kurjun-manager-api/src/main/java/io/subutai/core/kurjun/manager/api/dao/KurjunDataService.java
- management/server/core/kurjun-manager/kurjun-manager-impl/src/main/java/io/subutai/core/kurjun/manager/impl/KurjunManagerImpl.java
- management/server/core/kurjun-manager/kurjun-manager-impl/src/main/java/io/subutai/core/kurjun/manager/impl/dao/KurjunDataServiceImpl.java
- management/server/core/kurjun-manager/kurjun-manager-rest/src/main/java/io/subutai/core/kurjun/manager/rest/RestService.java
- management/server/core/kurjun-manager/kurjun-manager-rest/src/main/java/io/subutai/core/kurjun/manager/rest/RestServiceImpl.java
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsKurjun/service.js
Finished cleaning up Kujrun settings, added removing urls
> Cleaning up kurjun settings finished, added deleting urls

- agent/agent/alert/alert.go
- agent/cli/quota.go
- agent/main.go
https://github.com/subutai-io/subos/issues/189
> Added ability to set alert threshold.

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubEnvironmentManager.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/command/CommandUtil.java
- management/server/subutai-common/src/test/java/io/subutai/common/command/CommandUtilTest.java
> Core refactor

- agent/cli/stats.go
Added timeout for InfluxDB queries.
Added check of empty host name.
> Fixed freeze on subutai stats quota call. #614

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
env containers keys' clean
rh cert and public pgp key containers' in rh also cleaned
> fixes #745 #744 #748

- management/server/core/object-relation-manager/object-relation-manager-impl/src/main/java/io/subutai/core/object/relation/impl/RelationInfoManagerImpl.java
stop walking deeper once path is found
> fixed bug with container destroy

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/tasks/UsedHostNetResourcesTask.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
- management/server/server-karaf/pom.xml
- management/server/server-karaf/src/main/assembly/bin/setenv
fixed missing git_commit_id variable in pom
changed auto external IP detection to use algo: eth2->eth1->wan
> made XMX size 1GB

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
To download from global Kurjun properly
> * Changed downloading plugin to accept all SSL certificates

- management/Readme.md
> removed obsolete scripts

- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/SystemInfo.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/pojo/SystemInfoPojo.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/subutai-app/accountSettings/controller.js
- management/server/webui/src/main/webapp/subutai-app/common/partials/nav-menu.html
- management/server/webui/src/main/webapp/subutai-app/identity/service.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/service.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/settingsUpdates.js
Implemented update SS functionality.
> Implemented update SS functionality.

- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
Added cleaning up update notification on bar.
> Added cleaning up update notification on bar.

- agent/agent/container/container.go
- management/server/server-karaf/src/main/assembly/bin/influxdbinit.sh
> Updated influxdb version

- management/server/webui/src/main/webapp/subutai-app/login/controller.js
minor fix to authenticate with gpg signature
> Kurjun fixes

- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerWebClient.java
fixes #997 increased remote peer ping timeout
> offline peer fix

- management/server/core/bazaar-integration/bazaar-plugin-impl/src/main/java/io/subutai/core/bazaar/impl/BazaarImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ProductProcessor.java
- #1014 - added checks for dependencies and changed install/uninstall process accordingly.
- optdyn/hub#1257 - added new REST endpoint for requesting plugin info.
> Fixed #1014 and optdyn/hub#1257

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/local-peer/local-peer-rest/pom.xml
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/RestServiceImpl.java
- management/server/core/test/test-cli/pom.xml
- management/server/core/test/test-cli/src/main/java/io/subutai/core/test/cli/TestCommand.java
- management/server/core/test/test-cli/src/main/resources/OSGI-INF/blueprint/context.xml
200 - SS ready
500 - some modules failed
503 - not ready yet/ loading
> Added additional http codes to rest/v1/peer/ready endpoint:

- management/server/core/kurjun/kurjun-impl/src/main/java/io/subutai/core/kurjun/impl/TemplateManagerImpl.java
- management/server/core/kurjun/kurjun-impl/src/main/java/io/subutai/core/kurjun/impl/raw/RawManagerImpl.java
- management/server/core/kurjun/kurjun-impl/src/main/java/io/subutai/core/kurjun/impl/vapt/AptManagerImpl.java
> starts fetching metadata from gorjun in separate thread

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/destroy/DeletePeerStateHandler.java
Added SS side fix for issue https://github.com/subutai-io/plugins/issues/60
Also plugin side fix needed too @eabyshev
> Hub ss integration

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
and decreased timeout for p2p key renewal to 1  hour
> increased expiration timeout for p2p key to 3hr

- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/Commands.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/NetworkManagerImpl.java
- management/server/core/network-manager/network-manager-impl/src/test/java/io/subutai/core/network/impl/CommandsTest.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/SystemSettings.java
https://github.com/subutai-io/base/issues/1120
> Core cleanup

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/HostnameModificationWorkflow.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/ChangeHostnameStep.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/UpdateAuthorizedKeysStep.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/UpdateEtcHostsStep.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/helpers/RenameContainerTask.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/host-registry/host-registry-api/src/main/java/io/subutai/core/hostregistry/api/HostListener.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerCommands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestService.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestServiceImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/EnvironmentWebClient.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/RemotePeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/Peer.java
Implemented container hostname modification with updating hosts and authorized keys file
Parallelized implementation across peers
> Container hostname change

- management/server/core/command-executor/command-executor-impl/src/main/java/io/subutai/core/executor/impl/CommandProcessor.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/EnvironmentModifyWorkflow.java
- management/server/core/host-registry/host-registry-api/src/main/java/io/subutai/core/hostregistry/api/HostRegistry.java
- management/server/core/host-registry/host-registry-impl/src/main/java/io/subutai/core/hostregistry/impl/HostRegistryImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
- management/server/subutai-common/src/main/java/io/subutai/common/util/IPUtil.java
https://github.com/subutai-io/base/issues/1183
> Enable multiple rh

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestService.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/change/DomainStateHandler.java
https://github.com/optdyn/hub/issues/1817
> Added checks for proper domain assignment

- management/server/core/bazaar-integration/bazaar-plugin-impl/pom.xml
- management/server/core/bazaar-integration/bazaar-plugin-impl/src/main/java/io/subutai/core/bazaar/impl/BazaarImpl.java
- management/server/core/bazaar-integration/bazaar-plugin-impl/src/main/resources/OSGI-INF/blueprint/context.xml
Added preliminary handler for bundle events that will allow to handle manual bundle installations
#1267
> Issue 1267

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerCommands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
removed duplicate command
made ssh key manipulation commands consistent with each other
> Refactored ssh key commands

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
> Issue 1277

- management/server/core/identity-manager/identity-manager-api/src/main/java/io/subutai/core/identity/api/SessionManager.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/SessionManagerImpl.java
- management/server/core/identity-manager/identity-manager-impl/src/test/java/io/subutai/core/identity/impl/IdentityManagerImplTest.java
- management/server/core/identity-manager/identity-manager-impl/src/test/java/io/subutai/core/identity/impl/SessionManagerImplTest.java
Fixed session timeout and invalidation bug, by correcting SessionManager services
> Fixed session timeout and invalidation Bug

- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/RestService.java
- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/RestServiceImpl.java
- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/VEHServiceImpl.java
> Revert "Sonar critical"

- management/server/core/common-plugin/plugin-common/src/main/java/io/subutai/core/plugincommon/impl/PluginDataService.java
fixed sonar issue in PluginDataService.java
> Fixed critical sonar issue in PluginDataService.java

- management/pom.xml
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/core/identity-manager/identity-manager-rest-ui/src/main/java/io/subutai/core/identity/rest/ui/RestServiceImpl.java
- management/server/subutai-common/pom.xml
- management/server/subutai-common/src/main/java/io/subutai/common/environment/Topology.java
- management/server/subutai-common/src/main/java/io/subutai/common/util/StringUtil.java
- management/server/subutai-common/src/test/java/io/subutai/common/util/StringUtilTest.java
- management/server/webui/src/main/webapp/subutai-app/identityUser/controller.js
Created additional utility class that works with HTML parsers and validates input strings. Refactored Identity_Manager and Env-Manager to secure against XSS vulnerabilities
> Security impelemtations and protection against security vulnerabilities

- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
Fixed critical sonar issue. related to exception handling
> Critical Sonar issue fix

- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestServiceImpl.java
- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/transitional/RequestedHostJson.java
- management/server/core/host-registration/host-registration-rest/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/webui/src/main/webapp/css/style.css
- management/server/webui/src/main/webapp/subutai-app/nodeReg/controller.js
- management/server/webui/src/main/webapp/subutai-app/nodeReg/partials/view.html
> issue #1405

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HttpClient.java
…. Changed timeouts for http connections.
> merge asanaliev into subutai-io

- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/UpdateDto.java
- management/server/core/system-manager/system-manager-impl/pom.xml
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/dao/UpdateDao.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/entity/UpdateEntity.java
- management/server/core/system-manager/system-manager-impl/src/main/resources/META-INF/persistence.xml
- management/server/core/system-manager/system-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
added dao, entity and dto classes
> added db table for storing updates

- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/UpdateDto.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/entity/UpdateEntity.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
added two columns or commit ids
> added REST endpoint for UI

- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
> minor bugfix in dao query

- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/service.js
> Issue 1418

- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
> fixed path to ssl cert to be accessible by agent

- management/server/core/identity-manager/identity-manager-api/src/main/java/io/subutai/core/identity/api/IdentityManager.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/core/tracker/tracker-impl/src/main/java/io/subutai/core/tracker/impl/TrackerImpl.java
- management/server/core/tracker/tracker-impl/src/test/java/io/subutai/core/tracker/impl/TrackerImplTest.java
> Issue 1451

- management/server/core/identity-manager/identity-manager-api/src/main/java/io/subutai/core/identity/api/dao/IdentityDataService.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/dao/IdentityDataServiceImpl.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/dao/RoleDAO.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/dao/UserDAO.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/model/PermissionEntity.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/model/RoleEntity.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/model/UserDelegateEntity.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/model/UserEntity.java
- management/server/subutai-common/src/main/java/io/subutai/common/security/objects/PermissionScope.java
- management/server/webui/src/main/webapp/css/style.css
- management/server/webui/src/main/webapp/subutai-app/common/partials/nav-menu.html
- management/server/webui/src/main/webapp/subutai-app/identityRole/controller.js
> Issue 1453

- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/dao/UpdateDao.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/entity/UpdateEntity.java
> Issue 1455

- management/server/core/command-executor/command-executor-impl/src/main/java/io/subutai/core/executor/impl/CommandProcess.java
- management/server/core/command-executor/command-executor-impl/src/main/java/io/subutai/core/executor/impl/CommandProcessExpiryCallback.java
- management/server/core/command-executor/command-executor-impl/src/main/java/io/subutai/core/executor/impl/CommandProcessor.java
- management/server/core/command-executor/command-executor-impl/src/test/java/io/subutai/core/executor/impl/CommandProcessExpiryCallbackTest.java
- management/server/core/command-executor/command-executor-impl/src/test/java/io/subutai/core/executor/impl/CommandProcessTest.java
- management/server/core/command-executor/command-executor-impl/src/test/java/io/subutai/core/executor/impl/CommandProcessorTest.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
> Command timeout

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/HubEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/ProxyEnvironmentContainer.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/xpeer/RemoteEnvironment.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/entity/ContainerDto.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/entity/EnvironmentDto.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ConfigureContainerStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ReserveNetworkStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/destroy/DeletePeerStateHandler.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/HubEnvironment.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
Added functionality to correctly differentiate between Hub and SS environmentsor UI.
> Hub ssh key mgmt ss

- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/HubManager.java
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/model/Config.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/RegistrationManager.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/model/ConfigEntity.java
- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/RestServiceImpl.java
- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/pojo/RegistrationPojo.java
> added peerName to per config, and to REST DTO for diplay in UI

- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/index.html
#1500 Now if peer is registered with Hub, its peer name specified during registration will be displayed in page title
> Issue 1500

- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/service.js
> Issue 1493

- management/server/webui/src/main/webapp/subutai-app/console/service.js
> Issue 1507

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/LogListenerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/HubLoggerProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ResourceHostDataProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
> Issue 1478

- management/server/core/metric/metric-rest-ui/pom.xml
- management/server/core/metric/metric-rest-ui/src/main/java/io/subutai/core/metric/rest/ui/RestServiceImpl.java
- management/server/core/metric/metric-rest-ui/src/main/resources/OSGI-INF/blueprint/rest.xml
- management/server/webui/src/main/webapp/subutai-app/monitoring/controller.js
SS denied access to REST, fixed  #1512
> fixed bug with getting metrics for environment containers

- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/subutai-app/common/partials/login-header.html
> Show peer name

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
preparations for #1527 , cleanup
> Issue 1527

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/EnvironmentUserHelper.java
- management/server/core/identity-manager/identity-manager-api/src/main/java/io/subutai/core/identity/api/IdentityManager.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
> Issue 1531

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/ResourceHostCommands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
> fixes #1551

- management/server/webui/src/main/webapp/subutai-app/tenants/controller.js
> fixes #1553

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
Before all users env-s were uploaded to Hub on peer registration.
> upload only peer owners' environments

- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/partials/view.html
> Issue 1547

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
> added todo

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/EnvironmentManagerImplTest.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/common/HubAdapter.java
> Issue 1543

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/environment-manager/environment-manager-rest-ui/pom.xml
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/environment-manager/environment-manager-rest/pom.xml
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/EnvironmentDto.java
- management/server/webui/src/main/webapp/subutai-app/tenants/controller.js
Added user name to tenants environments table
> added column user to tenants table

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
For Hub environments user will be **hub** unless Hub supplies user info in metadata to SS
For x-peer env-s username will be shown as **remote**
For local env-s actual user name will be dispayed
> Fix tenant user

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/EnvironmentManagerImplTest.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestService.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/NetworkManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/EnvironmentContainerHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/SystemSettings.java
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/containers/partials/addToDomain.html
- management/server/webui/src/main/webapp/subutai-app/environment/service.js
Added ability to specify port when adding container to domain
> Add port to domain

- management/server/core/subutai-appender/pom.xml
- management/server/subutai-common/src/main/java/io/subutai/common/peer/Peer.java
- management/server/subutai-common/src/main/java/io/subutai/common/protocol/ReverseProxyConfig.java
- management/server/subutai-hub-share/src/test/java/io/subutai/hub/share/dto/SubutaiSystemLogTest.java
> minor refactor

- management/server/subutai-common/src/main/java/io/subutai/common/environment/NodeSchema.java
- management/server/subutai-common/src/main/java/io/subutai/common/protocol/Template.java
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
Added additional information on templates in UI  as tooltip
> Gorjun issue 64

- management/server/webui/src/main/webapp/subutai-app/environment/controller.js
> changed env  id to name in notification dialog

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/ConfigManager.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HttpClient.java
- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/VEHServiceUtil.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/MonitorImpl.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/server-karaf/src/main/assembly/etc/subutaisystem.cfg
- management/server/subutai-common/src/main/java/io/subutai/common/settings/SystemSettings.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/subutai-app/common/partials/hubSuccessMessage.html
- management/server/webui/src/main/webapp/subutai-app/common/partials/login-header.html
- management/server/webui/src/main/webapp/subutai-app/login/controller.js
- management/server/webui/src/main/webapp/subutai-app/login/service.js
> Issue 1596

- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
- management/server/webui/src/main/webapp/subutai-app/tracker/controller.js
> fixed sorting by date of tracker logs and updates history

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/dao/EnvironmentService.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/dao/EnvironmentServiceImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/EnvironmentManagerImplTest.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/dao/EnvironmentServiceImplTest.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/core/identity-manager/identity-manager-api/src/main/java/io/subutai/core/identity/api/IdentityManager.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/common/HubAdapter.java
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/containers/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/environment/service.js
> Issue 1610

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/HubManager.java
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/HubRequester.java
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/RestClient.java
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/RestResult.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/EnvironmentTelemetryProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/RegistrationManager.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/StateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/BuildContainerStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ConfigureContainerStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/change/ContainerStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/change/DomainStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/destroy/DeletePeerStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/http/HubRestClient.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ContainerEventProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/EnvironmentUserHelper.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/HeartbeatProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/HubLoggerProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/PeerMetricsProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/RegistrationRequestProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ResourceHostDataProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ResourceHostMonitorProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ResourceHostRegisterProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/VersionInfoProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/tunnel/TunnelEventProcessor.java
- management/server/core/hub-manager/hub-manager-rest/src/main/java/io/subutai/core/hubmanager/rest/RestServiceImpl.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/MonitorImpl.java
- management/server/server-karaf/src/main/assembly/etc/org.ops4j.pax.logging.cfg
- management/server/webui-impl/src/main/resources/subutai-app.js
> Issue 1613

- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/HubRequester.java
#1613 Restored stacktrace logging for exception thrown by process method of Hub requesting classes
> Stacktrace is back

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/PeerMetricsProcessor.java
refactored to use HubRequester
> Peer metrics

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestService.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/template-manager/template-manager-api/src/main/java/io/subutai/core/template/api/TemplateManager.java
- management/server/core/template-manager/template-manager-impl/src/main/java/io/subutai/core/template/impl/TemplateManagerImpl.java
- management/server/core/template-manager/template-manager-impl/src/test/java/io/subutai/core/template/impl/TemplateManagerImplTest.java
- management/server/core/test/test-cli/pom.xml
- management/server/core/test/test-cli/src/main/java/io/subutai/core/test/cli/TestCommand.java
- management/server/subutai-common/src/main/java/io/subutai/common/protocol/Template.java
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/service.js
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> Issue 1639

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/HostnameModificationWorkflow.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/ChangeHostnameStep.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/UpdateAuthorizedKeysStep.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/workflow/modification/HostnameModificationWorkflowTest.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerCommands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/test/java/io/subutai/core/localpeer/impl/LocalPeerCommandsTest.java
- management/server/core/local-peer/local-peer-impl/src/test/java/io/subutai/core/localpeer/impl/LocalPeerImplTest.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestService.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestServiceImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/EnvironmentWebClient.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/RemotePeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/Peer.java
> Issue 1642

- management/server/core/environment-manager/environment-manager-api/src/main/java/io/subutai/core/environment/api/EnvironmentManager.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerSecureProxy.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestService.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestService.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestServiceImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/EnvironmentWebClient.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/RemotePeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/Environment.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/EnvironmentDto.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/LocalPeer.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/RemotePeer.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/ChannelSettings.java
> Issue 1630

- management/server/webui/src/main/webapp/subutai-app/containers/partials/changeName.html
- management/server/webui/src/main/webapp/subutai-app/containers/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/popups/templateSettings.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/popups/templateSettingsAdvanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> fixes #1645

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/tasks/DeleteTunnelsTask.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/tasks/SetupTunnelsTask.java
- management/server/core/network-manager/network-manager-api/src/main/java/io/subutai/core/network/api/NetworkManager.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/Commands.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/NetworkManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/LocalPeer.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
> Issue 1658

- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
> Issue 1667

- management/server/core/host-registry/host-registry-impl/src/main/java/io/subutai/core/hostregistry/impl/HostRegistryImpl.java
- management/server/core/host-registry/host-registry-impl/src/test/java/io/subutai/core/hostregistry/impl/HostRegistryImplTest.java
- management/server/subutai-common/src/main/java/io/subutai/common/util/IPUtil.java
> removed mng-net interface from being used in communication with agent

- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsUpdates/partials/view.html
> Issue 1661

- management/server/core/host-registration/host-registration-api/src/main/java/io/subutai/core/registration/api/HostRegistrationManager.java
- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/HostRegistrationManagerImpl.java
- management/server/core/host-registration/host-registration-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestService.java
- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestServiceImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/ResourceHostCommands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/LocalPeer.java
- management/server/webui/src/main/webapp/subutai-app/nodeReg/controller.js
- management/server/webui/src/main/webapp/subutai-app/nodeReg/partials/changeName.html
- management/server/webui/src/main/webapp/subutai-app/nodeReg/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/nodeReg/service.js
> Issue 1677

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/lxc-quota-manager/lxc-quota-manager-api/src/main/java/io/subutai/core/lxc/quota/api/QuotaManager.java
- management/server/core/lxc-quota-manager/lxc-quota-manager-cli/src/main/java/io/subutai/core/lxc/quota/cli/GetQuota.java
- management/server/core/lxc-quota-manager/lxc-quota-manager-impl/src/main/java/io/subutai/core/lxc/quota/impl/Commands.java
- management/server/core/lxc-quota-manager/lxc-quota-manager-impl/src/main/java/io/subutai/core/lxc/quota/impl/QuotaManagerImpl.java
- management/server/core/lxc-quota-manager/lxc-quota-manager-impl/src/main/java/io/subutai/core/lxc/quota/impl/QuotaOutput.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/resource/ContainerResourceType.java
> added caching for container quotas

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/xpeer/RemoteEnvironment.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/ContainerDto.java
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
Fixed mixed up peers and rh names in edit environment advance mode.
> Advanced env manager

- management/pom.xml
- management/server/core/identity-manager/identity-manager-api/src/main/java/io/subutai/core/identity/api/model/Session.java
- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/model/SessionEntity.java
- management/server/core/identity-manager/identity-manager-rest-ui/pom.xml
- management/server/core/identity-manager/identity-manager-rest-ui/src/main/java/io/subutai/core/identity/rest/ui/RestService.java
- management/server/core/identity-manager/identity-manager-rest-ui/src/main/java/io/subutai/core/identity/rest/ui/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/java/io/subutai/webui/IndexFilter.java
- management/server/webui/src/main/java/io/subutai/webui/Login.java
- management/server/webui/src/main/webapp/index.html
- management/server/webui/src/main/webapp/subutai-app/accountSettings/controller.js
- management/server/webui/src/main/webapp/subutai-app/accountSettings/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/identity/service.js
#1671 SS now obtains Kurjun token for each user
> Issue 1671

- management/server/core/identity-manager/identity-manager-impl/src/main/java/io/subutai/core/identity/impl/IdentityManagerImpl.java
- management/server/core/identity-manager/identity-manager-rest-ui/src/main/java/io/subutai/core/identity/rest/ui/RestServiceImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/command/TemplateDownloadTracker.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/java/io/subutai/webui/IndexFilter.java
> Hotfix login

- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/HostRegistrationManagerImpl.java
- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/entity/RequestedHostImpl.java
- management/server/core/host-registration/host-registration-impl/src/test/java/io/subutai/core/registration/impl/entity/entity/RequestedHostImplTest.java
> fixes #1697

- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/containers/partials/view.html
> fixes #1696

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/EnvironmentModifyWorkflow.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/workflow/modification/EnvironmentModifyWorkflowTest.java
- management/server/core/tracker/tracker-impl/src/main/java/io/subutai/core/tracker/impl/TrackerOperationImpl.java
> fixes #1702

- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/template-manager/template-manager-api/src/main/java/io/subutai/core/template/api/TemplateManager.java
- management/server/core/template-manager/template-manager-impl/src/main/java/io/subutai/core/template/impl/TemplateManagerImpl.java
- management/server/webui/pom.xml
- management/server/webui/src/main/java/io/subutai/webui/Login.java
- management/server/webui/src/main/webapp/subutai-app/containers/partials/view.html
> Issue 1703

- management/server/webui/src/main/webapp/subutai-app/common/partials/nav-menu.html
renamed System Settings -> System
> minor naming tweak

- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/scripts/scripts.js
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
hide X icon when autosigning data with e2e plugin
> Hotfix ui tweaks

- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/scripts/scripts.js
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> Hotfix 1711

- management/server/core/host-registry/host-registry-api/src/main/java/io/subutai/core/hostregistry/api/HostRegistry.java
- management/server/core/host-registry/host-registry-impl/src/main/java/io/subutai/core/hostregistry/impl/HostRegistryImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/ResourceHostCommands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/test/test-cli/src/main/java/io/subutai/core/test/cli/TestCommand.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/util/ExceptionUtil.java
> Issue 1730

- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/NetworkSettings.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/pojo/NetworkSettingsPojo.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/server-karaf/pom.xml
- management/server/subutai-common/src/main/java/io/subutai/common/settings/SystemSettings.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/service.js
> Issue 1746

- management/server/core/tracker/tracker-impl/src/main/java/io/subutai/core/tracker/impl/TrackerImpl.java
- management/server/webui-impl/src/main/resources/subutai-app.js
- management/server/webui/src/main/webapp/subutai-app/login/controller.js
> Issue 1752

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/BuildContainerStateHandler.java
Fixes https://github.com/optdyn/hub/issues/2334
> fixes hub issue #2334

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/network-manager/network-manager-api/src/main/java/io/subutai/core/network/api/NetworkManager.java
- management/server/core/network-manager/network-manager-cli/src/main/java/io/subutai/core/network/cli/ListReservedPortsCommand.java
- management/server/core/network-manager/network-manager-cli/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/Commands.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/NetworkManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/protocol/Protocol.java
- management/server/subutai-common/src/main/java/io/subutai/common/protocol/ReservedPort.java
- management/server/subutai-common/src/main/java/io/subutai/common/protocol/ReservedPorts.java
> Issue 1755

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/HubEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/ProxyEnvironmentContainer.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/core/peer-manager/peer-manager-api/src/main/java/io/subutai/core/peer/api/PeerManager.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/EnvironmentWebClient.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
- management/server/core/peer-manager/peer-manager-rest-ui/src/main/java/io/subutai/core/peer/rest/ui/RestService.java
- management/server/core/peer-manager/peer-manager-rest-ui/src/main/java/io/subutai/core/peer/rest/ui/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ContainerHost.java
- management/server/webui/src/main/webapp/subutai-app/peerRegistration/controller.js
- management/server/webui/src/main/webapp/subutai-app/peerRegistration/partials/updateUrl.html
- management/server/webui/src/main/webapp/subutai-app/peerRegistration/service.js
> Issue 1759

- management/server/webui/src/main/webapp/subutai-app/environment/controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
> fixes #1683

- management/server/core/identity-manager/identity-manager-rest-ui/src/main/java/io/subutai/core/identity/rest/ui/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
removed usage of global Kurjun, SS now always uses local Kurjun
> now for any operation SS uses local Kurjun only

- management/server/core/karaf-manager/karaf-manager-impl/src/main/java/io/subutai/core/karaf/manager/impl/KarafManagerImpl.java
- management/server/core/peer-manager/peer-manager-api/src/main/java/io/subutai/core/peer/api/PeerManager.java
- management/server/core/peer-manager/peer-manager-cli/src/main/java/io/subutai/core/peer/cli/ApprovePeerCommand.java
- management/server/core/peer-manager/peer-manager-cli/src/main/java/io/subutai/core/peer/cli/CancelPeerCommand.java
- management/server/core/peer-manager/peer-manager-cli/src/main/java/io/subutai/core/peer/cli/RejectPeerCommand.java
- management/server/core/peer-manager/peer-manager-cli/src/main/java/io/subutai/core/peer/cli/UnregisterPeerCommand.java
- management/server/core/peer-manager/peer-manager-cli/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/dao/PeerRegistrationDataService.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/entity/PeerRegistrationData.java
- management/server/core/peer-manager/peer-manager-impl/src/main/resources/META-INF/persistence.xml
- management/server/core/peer-manager/peer-manager-rest-ui/src/main/java/io/subutai/core/peer/rest/ui/RestServiceImpl.java
> Hotfix 1767

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/creation/EnvironmentCreationWorkflow.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/creation/steps/ReservationStep.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/EnvironmentModifyWorkflow.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/workflow/modification/steps/ReservationStep.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/xpeer/RemoteEnvironment.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/workflow/creation/steps/ReservationStepTest.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/workflow/modification/steps/ReservationStepTest.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ReserveNetworkStateHandler.java
- management/server/core/local-peer/local-peer-cli/src/main/java/io/subutai/core/localpeer/cli/ReserveNetworkResourceCommand.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/NetworkResourceEntity.java
- management/server/subutai-common/src/main/java/io/subutai/common/network/NetworkResource.java
- management/server/subutai-common/src/main/java/io/subutai/common/network/NetworkResourceImpl.java
> Hotfix 1769

- management/server/webui/src/main/webapp/subutai-app/environment/controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
> displaying human readable size for templates

- management/server/server-karaf/pom.xml
- management/server/server-karaf/src/main/filtered-assembly/etc/subutaisystem.cfg
Added option -DhubEnv=[dev|hub|stage] to result in **hubIp** setting: [hub|dev|stage].subut.ai
> added variable to be able to set hub ip during build

- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/Commands.java
> changed format of commands to get p2p logs

- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/HostRegistrationManagerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
> added checks for RH and CH hostname

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ResourceHostDataProcessor.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/network-manager/network-manager-api/src/main/java/io/subutai/core/network/api/NetworkManager.java
- management/server/core/network-manager/network-manager-cli/src/main/java/io/subutai/core/network/cli/P2pLogsCommand.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/Commands.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/NetworkManagerImpl.java
- management/server/core/network-manager/network-manager-impl/src/test/java/io/subutai/core/network/impl/CommandsTest.java
- management/server/core/network-manager/network-manager-impl/src/test/java/io/subutai/core/network/impl/NetworkManagerImplTest.java
- management/server/subutai-common/src/main/java/io/subutai/common/network/JournalCtlLevel.java
- management/server/subutai-common/src/main/java/io/subutai/common/network/LogLevel.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
> added intial implementation #1789

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/PeerMetricsProcessor.java
- management/server/subutai-common/src/main/java/io/subutai/common/metric/HistoricalMetrics.java
fixed NPE during peer registration
> Fix p2p logs

- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/EnvironmentWebClient.java
> minor precondition fix

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ReserveNetworkStateHandler.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/dto/environment/EnvironmentInfoDto.java
> added ownername field to DTO #1856

- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/RestServiceImpl.java
Hardcoded min number of bundles to be loaded before the endpoint returns http code 200
> Fix ready endpoint

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
- management/server/subutai-common/src/main/java/io/subutai/common/host/ResourceHostInfo.java
- management/server/subutai-common/src/main/java/io/subutai/common/host/ResourceHostInfoModel.java
> Hotfix 1924

- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
> #1924 optimization

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
> #1917 decreased interval for env upload from SC to Hub to 10 minutes

- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
https://github.com/subutai-io/base/issues/1946
> Hotfix 1946

- management/server/core/host-registration/host-registration-api/src/main/java/io/subutai/core/registration/api/HostRegistrationManager.java
- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/HostRegistrationManagerImpl.java
- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestService.java
- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestServiceImpl.java
- management/server/webui/src/main/webapp/subutai-app/nodeReg/controller.js
- management/server/webui/src/main/webapp/subutai-app/nodeReg/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/nodeReg/service.js
fixes RH approval, removal functionality
> Fix rh removal

- Readme.md
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/HubManager.java
- management/server/core/hub-manager/hub-manager-api/src/main/java/io/subutai/core/hubmanager/api/RestResult.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/ConfigManager.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/EnvironmentTelemetryProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/appscale/AppScaleProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/StateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/change/DomainStateHandler.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/http/HubRestClient.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ContainerEventProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/HubLoggerProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/PeerMetricsProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/ProductProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/SystemConfProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/UserTokenProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/tunnel/TunnelEventProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/tunnel/TunnelHelper.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/tunnel/TunnelProcessor.java
- management/server/core/hub-manager/hub-manager-impl/src/main/resources/OSGI-INF/blueprint/context.xml
> Support for prevent hub crash

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/test/java/io/subutai/core/environment/impl/entity/EnvironmentContainerImplTest.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ContainerHostEntity.java
- management/server/core/local-peer/local-peer-impl/src/test/java/io/subutai/core/localpeer/impl/LocalPeerImplTest.java
- management/server/core/local-peer/local-peer-impl/src/test/java/io/subutai/core/localpeer/impl/entity/ContainerHostEntityTest.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestService.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/EnvironmentRestServiceImpl.java
- management/server/core/metric/metric-api/src/main/java/io/subutai/core/metric/api/Monitor.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/Commands.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/MonitorImpl.java
- management/server/core/metric/metric-impl/src/test/java/io/subutai/core/metric/impl/MonitorImplTest.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/RemotePeerImpl.java
- management/server/core/peer-manager/peer-manager-impl/src/test/java/io/subutai/core/peer/impl/RemotePeerImplTest.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ContainerHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/EnvironmentContainerHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/Peer.java
removed obsolete _monitor.getProcessResourceUsage_ method
support for https://github.com/subutai-io/plugins/issues/161
> plugins-161 

- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/HostRegistrationManagerImpl.java
- management/server/webui/src/main/webapp/subutai-app/nodeReg/controller.js
- management/server/webui/src/main/webapp/subutai-app/nodeReg/partials/view.html
added display of RH id in Resource Hosts page and ability to remove unapproved yet RH registration request
> added display of RH id

- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestServiceImpl.java
fixed error in displaying RHs when RH-with-MH is not registered yet
> fixed error in displaying RHs when RH-with-MH is not registered yet

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/adapter/HubAdapterImpl.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/common/HubAdapter.java
added handling http error when uploading local env to Hub, so that unsuccessful http codes will case later reupload attempt
> https://github.com/optdyn/hub/issues/3520

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
> fix bug with wrong calculation of resource values for logging

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> changed default container size to TINY

- management/server/subutai-common/src/main/java/io/subutai/common/cache/CacheEntry.java
- management/server/subutai-common/src/main/java/io/subutai/common/cache/CacheEntryWithExpiryCallback.java
- management/server/subutai-common/src/main/java/io/subutai/common/cache/EntryExpiryCallback.java
- management/server/subutai-common/src/main/java/io/subutai/common/cache/ExpiringCache.java
> Hotfix 2015

- management/server/webui/src/main/webapp/subutai-app/common/partials/login-header.html
added "hub-button" id to hub button div to simplify serenity test
> #2030  fixed serenity tests

- management/server/webui/src/main/webapp/css/style.css
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/advanced.html
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> Hotfix 1861

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/ResourceHostCapacity.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/RestServiceImpl.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/Commands.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/MonitorImpl.java
- management/server/core/metric/metric-impl/src/test/java/io/subutai/core/metric/impl/CommandsTest.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/RemotePeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/Nodes.java
- management/server/subutai-common/src/main/java/io/subutai/common/metric/HistoricalMetrics.java
- management/server/subutai-common/src/main/java/io/subutai/common/util/UnitUtil.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/quota/ContainerSize.java
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
> Hotfix 2051

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ExchangeInfoStateHandler.java
> #2056 removed resource sufficiency check for Hub environments

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/binding/Commands.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/tasks/UsedHostNetResourcesTask.java
- management/server/core/local-peer/local-peer-impl/src/test/java/io/subutai/core/localpeer/impl/tasks/UsedHostNetResourcesTaskTest.java
- management/server/core/network-manager/network-manager-api/src/main/java/io/subutai/core/network/api/NetworkManager.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/Commands.java
- management/server/core/network-manager/network-manager-impl/src/main/java/io/subutai/core/network/impl/NetworkManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/command/RequestBuilder.java
- management/server/subutai-common/src/main/java/io/subutai/common/network/UsedNetworkResources.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
- management/server/subutai-common/src/main/java/io/subutai/common/settings/Common.java
- management/server/subutai-common/src/main/java/io/subutai/common/util/P2PUtil.java
- management/server/subutai-common/src/test/java/io/subutai/common/command/RequestBuilderTest.java
#2058 removed workaround , implemented proper way to check reserved p2p names
> Hotfix 2058

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/template-manager/template-manager-impl/src/main/java/io/subutai/core/template/impl/TemplateManagerImpl.java
- fix bug with empty quotas for predefined size
- disabled resource check for resource sufficiency
- in case Gorjun accidentally returns empty metadata for a verified template lookup, we need to return not found response instead of partial metadata
> Hotfix 2074

- Readme.md
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/AdvancedSettings.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/pojo/AdvancedSettingsPojo.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/controller.js
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/partials/karaflogs.html
- management/server/webui/src/main/webapp/subutai-app/settingsAdvanced/service.js
> Hotfix 2073

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
https://github.com/optdyn/hub/issues/3720
> #hub-3720 added check for the only container in Hub env

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/HeartbeatProcessor.java
>  added remote check on HUb before deleting registration record

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/adapter/EnvironmentAdapter.java
changed log level for the "hub environment not found" case  from ERR to WARN
> fix log level

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/util/EnvironmentUserHelper.java
- management/server/core/template-manager/template-manager-impl/src/main/java/io/subutai/core/template/impl/TemplateManagerImpl.java
added additional checks to fill template cache asap
> added additional checks to fill template cache asap

- management/server/core/tracker/tracker-impl/src/main/java/io/subutai/core/tracker/impl/TrackerOperationImpl.java
- management/server/core/tracker/tracker-impl/src/main/java/io/subutai/core/tracker/impl/TrackerOperationViewImpl.java
- management/server/core/tracker/tracker-impl/src/test/java/io/subutai/core/tracker/impl/TrackerOperationImplTest.java
- management/server/webui/src/main/webapp/subutai-app/about/partials/about.html
>  now double quote and curly brackets are removed from log message

- management/server/core/host-registry/host-registry-impl/src/main/java/io/subutai/core/hostregistry/impl/HostRegistryImpl.java
- management/server/core/host-registry/host-registry-impl/src/test/java/io/subutai/core/hostregistry/impl/HostRegistryImplTest.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/NetworkResourceEntity.java
- management/server/subutai-common/src/main/java/io/subutai/common/host/ContainerHostInfoModel.java
- management/server/subutai-common/src/main/java/io/subutai/common/host/ResourceHostInfoModel.java
fix p2p swarms cleanup on late container host registration
> Fix wrong env cleanup

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/command/TemplateDownloadTracker.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/command/TemplateUploadTracker.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntity.java
- management/server/core/local-peer/local-peer-impl/src/test/java/io/subutai/core/localpeer/impl/entity/ResourceHostEntityTest.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/RestService.java
- management/server/core/local-peer/local-peer-rest/src/main/java/io/subutai/core/localpeer/rest/RestServiceImpl.java
- management/server/core/template-manager/template-manager-impl/src/main/java/io/subutai/core/template/impl/TemplateManagerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/PeerTemplatesUploadProgress.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/RhTemplatesUploadProgress.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/LocalPeer.java
- management/server/subutai-common/src/main/java/io/subutai/common/peer/ResourceHost.java
- management/server/webui/src/main/webapp/scripts/scripts.js
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/containers/partials/uploadProgress.html
- management/server/webui/src/main/webapp/subutai-app/environment/service.js
> display of template upload progress

- management/server/core/environment-manager/environment-manager-cli/src/test/java/io/subutai/core/environment/cli/GetContainerQuotaCommandTest.java
- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-rest/pom.xml
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestService.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/Node.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/Topology.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/quota/ContainerSize.java
Added REST endpoints for creating environment and modifying it:
1) Create environment: 
```{
"name": "my-awesome-environment",
"sshKey": "place-your-ssh-key-here}",
"placement": {
"place-peer-id-here": [
{
"name": "my-awesome-container",
"quota": {
"containerSize": "TINY"
},
"hostId": "place-rh-id-here",
"templateId": "place-template-id-here"
}
]
}
}```
simplified version for local peer only:
```{
"name": "my-awesome-environment",
"placement": {
"local": [
{
"name": "my-awesome-container",
"templateName": "ubuntu16"
}
]
}
}```
2) Modify environment: add 1 container to existing environment
`PUT /rest/v1/environments/{environment-id} `
```{
"name": "my-awesome-environment",
"placement": {
"local": [
{
"name": "my-awesome-container",
"templateName": "ubuntu16"
}
]
}
}```
> Add environment management REST

- management/server/webui/src/main/webapp/css/style.css
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/containers/partials/uploadProgress.html
fixed bug with subsequent upload of the samely named templates
> improved display of percentage

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/entity/LocalEnvironment.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestService.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/environment/Topology.java
Added destroyContainer and destroyEnvironment REST endpoints
Destroy environment `DELETE /rest/v1/environments/{environment-id}`
Destroy container `DELETE /rest/v1/environments/containers/{container-id}`
> Env mgmt rest

- management/server/core/tracker/tracker-impl/src/main/java/io/subutai/core/tracker/impl/TrackerOperationImpl.java
> removing line breaks from tracker log

- management/server/core/environment-manager/environment-manager-impl/src/main/java/io/subutai/core/environment/impl/EnvironmentManagerImpl.java
- management/server/core/environment-manager/environment-manager-rest-ui/src/main/java/io/subutai/core/environment/rest/ui/RestServiceImpl.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/EnvironmentCreationDto.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/NodeDto.java
- management/server/core/environment-manager/environment-manager-rest/src/main/java/io/subutai/core/environment/rest/RestServiceImpl.java
added env mgmt REST
https://github.com/subutai-io/base/issues/2127
> Hotfix rest

- Jenkinsfile
> added optional shKey param to dto

- management/server/core/peer-manager/peer-manager-api/src/main/java/io/subutai/core/peer/api/PeerManager.java
- management/server/core/peer-manager/peer-manager-cli/src/main/java/io/subutai/core/peer/cli/SetPublicUrlCommand.java
- management/server/core/peer-manager/peer-manager-impl/src/main/java/io/subutai/core/peer/impl/PeerManagerImpl.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/SystemManager.java
- management/server/core/system-manager/system-manager-api/src/main/java/io/subutai/core/systemmanager/api/pojo/NetworkSettings.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/SystemManagerImpl.java
- management/server/core/system-manager/system-manager-impl/src/main/java/io/subutai/core/systemmanager/impl/pojo/NetworkSettingsPojo.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestService.java
- management/server/core/system-manager/system-manager-rest/src/main/java/io/subutai/core/systemmanager/rest/RestServiceImpl.java
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/partials/view.html
- management/server/webui/src/main/webapp/subutai-app/settingsNetwork/service.js
> Issue 2320

- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/command/TemplateDownloadTracker.java
> Sysnet->Dev

- Jenkinsfile
> Dev -> Master

- management/server/webui/src/main/webapp/subutai-app/console/controller.js
> #2220 "HTML not stripped in container cli output"

- management/server/webui/src/main/webapp/subutai-app/common/partials/login-header.html
On peer registration form cursor is jumping to first text box
> #2481 -> Dev

- Jenkinsfile
- management/server/webui/src/main/webapp/subutai-app/common/partials/login-header.html
On peer registration form cursor is jumping to first text box
> #2481 Dev -> Master 

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/processor/HeartbeatProcessor.java
Host disconnected exception after peer restart
> #2562 -> Dev

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/requestor/P2pLogsSender.java
- management/server/core/metric/metric-api/src/main/java/io/subutai/core/metric/api/Monitor.java
- management/server/core/metric/metric-api/src/main/java/io/subutai/core/metric/api/pojo/P2PInfo.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/MonitorImpl.java
- management/server/core/metric/metric-impl/src/main/java/io/subutai/core/metric/impl/pojo/P2PInfoPojo.java
- management/server/core/metric/metric-rest-ui/src/main/java/io/subutai/core/metric/rest/ui/RestService.java
- management/server/core/metric/metric-rest-ui/src/main/java/io/subutai/core/metric/rest/ui/RestServiceImpl.java
- management/server/core/metric/metric-rest-ui/src/main/java/io/subutai/core/metric/rest/ui/pojo/P2PInfoPojo.java
- management/server/subutai-hub-share/src/main/java/io/subutai/hub/share/dto/P2PDto.java
- management/server/webui/src/main/webapp/subutai-app/monitoring/controller.js
- management/server/webui/src/main/webapp/subutai-app/monitoring/partials/graphs.html
- management/server/webui/src/main/webapp/subutai-app/monitoring/service.js
> #2578  Dev -> Master

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/HubManagerImpl.java
- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/requestor/P2pStatusSender.java
- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/advanced-controller.js
- management/server/webui/src/main/webapp/subutai-app/environment/partials/simple.html
- management/server/webui/src/main/webapp/subutai-app/environment/simple-controller.js
Console UI should allow container names that meet ARPANET hostname requirements only
> #2588 -> Dev

- management/server/core/host-registration/host-registration-impl/src/main/java/io/subutai/core/registration/impl/entity/ContainerInfoImpl.java
- management/server/core/host-registration/host-registration-rest/src/main/java/io/subutai/core/registration/rest/RegistrationRestServiceImpl.java
- management/server/core/local-peer/local-peer-impl/src/main/java/io/subutai/core/localpeer/impl/LocalPeerImpl.java
- management/server/subutai-common/src/main/java/io/subutai/common/host/Quota.java
https://github.com/subutai-io/agent/issues/717
> support for agent-717

- management/server/webui/src/main/webapp/subutai-app/common/partials/login-header.html
- management/server/webui/src/main/webapp/subutai-app/monitoring/controller.js
- management/server/webui/src/main/webapp/subutai-app/monitoring/partials/graphs.html
removed p2p status from irrelevant tabs
> #2600 Dev -> Master 

- management/pom.xml
- management/server/core/metric/metric-rest-ui/build.gradle
- management/server/server-karaf/pom.xml
> Maven nexus

- management/server/core/hub-manager/hub-manager-impl/src/main/java/io/subutai/core/hubmanager/impl/environment/state/build/ConfigureEnvironmentStateHandler.java
Revert "Fixed bazaar issue 5470, refactored passing ansible extra variables through json file."
This reverts commit 9c00c91
> Fix BP operation

- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/ConfigManager.java
- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/http/BazaarRestClient.java
- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/requestor/VersionInfoProcessor.java
- management/server/subutai-bazaar-share/src/main/java/io/subutai/bazaar/share/dto/PeerInfoDto.java
- management/server/subutai-bazaar-share/src/main/java/io/subutai/bazaar/share/dto/RhVersionInfoDto.java
- management/server/subutai-bazaar-share/src/main/java/io/subutai/bazaar/share/dto/VersionInfoDto.java
modified VersionInfoProcessor - creating a new method to send peer version info; added RhVersionInfoDto; now version info will send by PeerInfoDto about all RH which peer has; deprecated VersionInfoDto.
> Version info mod

- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/processor/ProxyProcessor.java
- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/processor/port_map/DestroyPortMap.java
- management/server/subutai-bazaar-share/src/main/java/io/subutai/bazaar/share/dto/domain/PortMapDto.java
Added check if port mapping exists, before attempt to delete it, in ProxyHandler.
Added 'correlationId' to proxy port mapping commands.
> Fixed handling proxy port mapping in proper order (optdyn/hub#7645).

- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/environment/state/create/BuildContainerStateHandler.java
> Fixed no task error

- management/server/webui/src/main/webapp/subutai-app/containers/controller.js
- management/server/webui/src/main/webapp/subutai-app/containers/partials/manageSnapshots.html
> Issue 2821

- management/server/core/bazaar-manager/bazaar-manager-impl/src/main/java/io/subutai/core/bazaarmanager/impl/environment/state/backup/BackupStateHandler.java
Fixed bug when newly created snapshot date was reset to null in backup response.
> Support for taking backup via Bazaar

- Jenkinsfile
> Experimental buster build
